spring.application.name=DocMind

# PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/docmind
spring.datasource.username=postgres
spring.datasource.password=1234567

# Ollama

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text


# PGVector

#spring.ai.vectorstore.pgvector.initialize-schema=true
#spring.ai.vectorstore.pgvector.index-type=HNSW
#spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE